/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdiadosRouteImport } from './routes/adiados'
import { Route as ArquivadosRouteImport } from './routes/arquivados'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as EnviadosRouteImport } from './routes/enviados'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LixeiraRouteImport } from './routes/lixeira'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as RascunhosRouteImport } from './routes/rascunhos'
import { Route as SpamRouteImport } from './routes/spam'
import { Route as PastaSlugRouteImport } from './routes/pasta.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdiadosRoute = AdiadosRouteImport.update({
  id: '/adiados',
  path: '/adiados',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivadosRoute = ArquivadosRouteImport.update({
  id: '/arquivados',
  path: '/arquivados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviadosRoute = EnviadosRouteImport.update({
  id: '/enviados',
  path: '/enviados',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LixeiraRoute = LixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const RascunhosRoute = RascunhosRouteImport.update({
  id: '/rascunhos',
  path: '/rascunhos',
  getParentRoute: () => rootRouteImport,
} as any)
const SpamRoute = SpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => rootRouteImport,
} as any)
const PastaSlugRoute = PastaSlugRouteImport.update({
  id: '/pasta/$slug',
  path: '/pasta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adiados': typeof AdiadosRoute
  '/arquivados': typeof ArquivadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contatos': typeof ContatosRoute
  '/enviados': typeof EnviadosRoute
  '/favoritos': typeof FavoritosRoute
  '/lixeira': typeof LixeiraRoute
  '/minha-conta': typeof MinhaContaRoute
  '/rascunhos': typeof RascunhosRoute
  '/spam': typeof SpamRoute
  '/pasta/$slug': typeof PastaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adiados': typeof AdiadosRoute
  '/arquivados': typeof ArquivadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contatos': typeof ContatosRoute
  '/enviados': typeof EnviadosRoute
  '/favoritos': typeof FavoritosRoute
  '/lixeira': typeof LixeiraRoute
  '/minha-conta': typeof MinhaContaRoute
  '/rascunhos': typeof RascunhosRoute
  '/spam': typeof SpamRoute
  '/pasta/$slug': typeof PastaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adiados': typeof AdiadosRoute
  '/arquivados': typeof ArquivadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contatos': typeof ContatosRoute
  '/enviados': typeof EnviadosRoute
  '/favoritos': typeof FavoritosRoute
  '/lixeira': typeof LixeiraRoute
  '/minha-conta': typeof MinhaContaRoute
  '/rascunhos': typeof RascunhosRoute
  '/spam': typeof SpamRoute
  '/pasta/$slug': typeof PastaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adiados'
    | '/arquivados'
    | '/configuracoes'
    | '/contas'
    | '/contatos'
    | '/enviados'
    | '/favoritos'
    | '/lixeira'
    | '/minha-conta'
    | '/rascunhos'
    | '/spam'
    | '/pasta/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adiados'
    | '/arquivados'
    | '/configuracoes'
    | '/contas'
    | '/contatos'
    | '/enviados'
    | '/favoritos'
    | '/lixeira'
    | '/minha-conta'
    | '/rascunhos'
    | '/spam'
    | '/pasta/$slug'
  id:
    | '__root__'
    | '/'
    | '/adiados'
    | '/arquivados'
    | '/configuracoes'
    | '/contas'
    | '/contatos'
    | '/enviados'
    | '/favoritos'
    | '/lixeira'
    | '/minha-conta'
    | '/rascunhos'
    | '/spam'
    | '/pasta/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdiadosRoute: typeof AdiadosRoute
  ArquivadosRoute: typeof ArquivadosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  ContatosRoute: typeof ContatosRoute
  EnviadosRoute: typeof EnviadosRoute
  FavoritosRoute: typeof FavoritosRoute
  LixeiraRoute: typeof LixeiraRoute
  MinhaContaRoute: typeof MinhaContaRoute
  RascunhosRoute: typeof RascunhosRoute
  SpamRoute: typeof SpamRoute
  PastaSlugRoute: typeof PastaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adiados': {
      id: '/adiados'
      path: '/adiados'
      fullPath: '/adiados'
      preLoaderRoute: typeof AdiadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivados': {
      id: '/arquivados'
      path: '/arquivados'
      fullPath: '/arquivados'
      preLoaderRoute: typeof ArquivadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviados': {
      id: '/enviados'
      path: '/enviados'
      fullPath: '/enviados'
      preLoaderRoute: typeof EnviadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lixeira': {
      id: '/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof LixeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rascunhos': {
      id: '/rascunhos'
      path: '/rascunhos'
      fullPath: '/rascunhos'
      preLoaderRoute: typeof RascunhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spam': {
      id: '/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof SpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasta/$slug': {
      id: '/pasta/$slug'
      path: '/pasta/$slug'
      fullPath: '/pasta/$slug'
      preLoaderRoute: typeof PastaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdiadosRoute: AdiadosRoute,
  ArquivadosRoute: ArquivadosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  ContatosRoute: ContatosRoute,
  EnviadosRoute: EnviadosRoute,
  FavoritosRoute: FavoritosRoute,
  LixeiraRoute: LixeiraRoute,
  MinhaContaRoute: MinhaContaRoute,
  RascunhosRoute: RascunhosRoute,
  SpamRoute: SpamRoute,
  PastaSlugRoute: PastaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
